<?php

/**
 * @file
 * Provides optimised images via http://kraken.io.
 */

/**
 * Implements hook_help().
 */
function kraken_help($path, $arg) {
  switch ($path) {
    // Main module help for the kraken module
    case 'admin/help#kraken':
      return '<p>' . t('Getting the highest quality images with the smallest file sizes can be difficult. <ahref="@krakenio">Kraken.io</a> provides a service to optimize your images and strikes a good balance between high image quality with small file sizes. This module submits the images users provide in their normal content adding and editing to Kraken.io and Kraken.io provides an optimized version which is stored locally. Configuring the kraken module is done on the <a href="@img_toolkit">image toolkit page</a>.', array('@img_toolkit' => url('admin/config/media/image-toolkit'), '@krakenio' => url('http://kraken.io'))) . '</p>';
  }
}

/**
 * Implements hook_libraries_info().
 */
function kraken_libraries_info() {
  $libraries['kraken-php'] = array(
    'name' => 'kraken-php',
    'vendor url' => 'http://kraken.io',
    'download url' => 'https://github.com/kraken-io/kraken-php',
    'version' => '',
    'path' => 'lib',
    'files' => array(
      'php' => array('Kraken.php'),
    ),
  );
  return $libraries;
}
/**
 * Implements hook_form_FORM_ID_alter().
 */
function kraken_form_system_image_toolkit_settings_alter(&$form, &$form_state) {
  $form['kraken'] = array(
  '#type' => 'container',
  '#tree' => TRUE,
);
  if (!function_exists('libraries_get_libraries')) {
    $form['kraken']['library'] = array(
      '#type' => 'markup',
      '#markup' => t('Kraken io integration requires both:
        <ul><li>the <a href = "http://drupal.org/project/libraries">Libraries</a> module;</li>
        <li>the <a href="https://github.com/kraken-io/kraken-php">Kraken-PHP library</a>
        to be installed in your libraries folder as kraken-php (sites/all/libraries/kraken-php).</li></ul>'),
    );
  }
  else {
    $libraries = libraries_detect('kraken-php');
    dsm($libraries);
    if ($libraries['error']) {
      $form['kraken']['library'] = array(
        '#type' => 'markup',
        '#markup' => t("!error_msg Kraken.io integration requires the <a href=\"https://github.com/kraken-io/kraken-php\">Kraken-PHP library</a> to be installed in your libraries folder as kraken-php (sites/all/libraries/kraken-php).", array('!error_msg' => $libraries['error message'])),
      );
    }
    else {

      $form['kraken']['api_key'] = array(
        '#title' => t('API Key'),
        '#type' => 'textfield',
        '#default_value' => variable_get('kraken_api_key', ''),
      );

      $form['kraken']['api_secret'] = array(
        '#title' => t('API Secret'),
        '#type' => 'textfield',
        '#default_value' => variable_get('kraken_api_secret', ''),
      );
      $form['#submit'][] = 'kraken_image_toolkit_settings_submit';
    }
  }
}

/**
 * Form submit for system_image_toolkit_settings.
 */
function kraken_image_toolkit_settings_submit(&$form, &$form_state) {
  $values = $form_state['values'];
  if (!empty($values['kraken']['api_key'])) {
    variable_set('kraken_api_key', $values['kraken']['api_key']);
  }
  if (!empty($values['kraken']['api_secret'])) {
    variable_set('kraken_api_secret', $values['kraken']['api_secret']);
  }
}

/**
 * Implements hook_image_effect_info().
 */
function kraken_image_effect_info() {
  $effects = array();
  $effects['kraken_optimize'] = array(
    'label' => t('Kraken optimize'),
    'help' => t('The <a href="@kraken_io">Kraken.io</a> service optimizes the quality of the image and minimizes file size.', array('@kraken_io' => url('http://kraken.io'))),
    'effect callback' => 'kraken_optimize',
  );
  return $effects;
}

/**
 * Callback to optimize the image with the kraken.io service.
 */
function kraken_optimize(&$image, $data) {
  
}

